import type { Candidate, Evidence, Recommendation, Score, StartupAnalysis } from "../core/models.js";

export type MemoInput = { candidate: Candidate; evidence: Evidence[]; analysis: StartupAnalysis; score: Score; recommendation: Recommendation };

export function renderMemo(input: MemoInput): string {
  const { candidate, evidence, analysis, score, recommendation } = input;
  const decisionClass = recommendation.decision.toLowerCase().replaceAll(" ", "-");
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${escape(candidate.name)} | DealScout</title><style>${styles()}</style></head><body><main class="memo"><header><p class="eyebrow">DEALSCOUT / INVESTMENT SNAPSHOT</p><div class="hero"><div><h1>${escape(candidate.name)}</h1><p class="lede">${escape(candidate.description)}</p></div><aside class="score"><span>${score.total}</span><small>/ 100</small><strong class="${decisionClass}">${escape(recommendation.decision)}</strong></aside></div><p class="meta"><a href="${escape(candidate.website)}">Company website</a> · ${escape(candidate.signal)} · ${escape(candidate.source)}</p></header><section class="callout"><h2>Investment call</h2><p>${escape(recommendation.rationale)}</p></section><div class="grid"><section><h2>Product</h2><p>${escape(analysis.product)}</p></section><section><h2>Team</h2><p>${escape(analysis.team)}</p></section><section><h2>Market</h2><p>${escape(analysis.market)}</p></section><section><h2>Traction</h2><p>${escape(analysis.traction)}</p></section></div><section><h2>Risks and open questions</h2>${list([...analysis.risks, ...analysis.openQuestions])}</section><section><h2>What would change our mind</h2>${list(recommendation.mindChanges)}</section><section><h2>Evidence</h2><div class="evidence">${evidence.map((item) => `<a href="${escape(item.url)}" target="_blank" rel="noreferrer"><b>${escape(item.source)}</b><span>${escape(item.claim)}</span></a>`).join("")}</div></section></main></body></html>`;
}

export function renderRunReport(topic: string, entries: MemoInput[]): string {
  const cards = entries.map(({ candidate, score, recommendation }) => `<a class="card" href="memos/${slug(candidate.name)}.html"><span class="${recommendation.decision.toLowerCase().replaceAll(" ", "-")}">${escape(recommendation.decision)}</span><h2>${escape(candidate.name)}</h2><p>${escape(candidate.description)}</p><b>${score.total}/100</b></a>`).join("");
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>DealScout run</title><style>${styles()}</style></head><body><main class="memo"><header><p class="eyebrow">DEALSCOUT / PIPELINE RUN</p><h1>${escape(topic)}</h1><p class="lede">${entries.length} researched startup candidates</p></header><div class="cards">${cards}</div></main></body></html>`;
}

function list(items: string[]): string { return `<ul>${items.map((item) => `<li>${escape(item)}</li>`).join("")}</ul>`; }
function slug(name: string): string { return name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, ""); }
function escape(value: string): string { return value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;"); }
function styles(): string { return `:root{--ink:#17252a;--paper:#f8f3e8;--teal:#175b58;--line:#d8cfbc}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 80% 0,#dbe8df,transparent 35%),var(--paper);color:var(--ink);font:16px Georgia,serif}.memo{max-width:980px;margin:auto;padding:56px 24px 80px}.eyebrow{font:700 12px Arial,sans-serif;letter-spacing:.15em;color:var(--teal)}h1{font-size:clamp(42px,7vw,74px);line-height:.95;margin:12px 0}.hero{display:flex;gap:30px;justify-content:space-between}.lede{font-size:22px;line-height:1.45;max-width:680px}.score{min-width:150px;padding:18px;border:1px solid var(--line);text-align:center;background:#fffaf0}.score span{font:700 54px Arial,sans-serif}.score strong,.card span{display:block;margin-top:8px;font:700 12px Arial,sans-serif;letter-spacing:.1em}.watch{color:#9b6500}.pass{color:#9c3c31}.take-a-meeting{color:var(--teal)}.meta{font:14px Arial,sans-serif}.meta a{color:var(--teal)}section,.callout{margin-top:30px;padding-top:20px;border-top:1px solid var(--line)}h2{font:700 20px Arial,sans-serif;margin:0 0 12px}.callout{background:var(--teal);color:#fff;padding:24px;border:0}.grid,.cards{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px}.grid section{margin:0}.evidence{display:grid;gap:10px}.evidence a,.card{color:inherit;text-decoration:none;background:#fffaf0;border:1px solid var(--line);padding:14px;display:grid;gap:5px}.evidence b{font:12px Arial,sans-serif;color:var(--teal);text-transform:uppercase}.cards{grid-template-columns:repeat(3,minmax(0,1fr));margin-top:34px}.card h2{font-size:23px}.card:hover{transform:translateY(-3px);transition:.18s ease}@media(max-width:640px){.hero,.grid,.cards{grid-template-columns:1fr;display:grid}.score{width:100%}}`; }
